language: python
python:
    #- "2.7"
    - "3.5.3" # currently breaks with 3.6, possibly need a different version of wxPython for 3.6
    # command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors

addons:
  apt:
    packages: # basically wxPython dependencies
    - libwebkitgtk-dev
    - libjpeg-dev
    - libtiff-dev
    - libgtk2.0-dev
    - libsdl1.2-dev
    - libgstreamer-plugins-base0.10-dev
    - freeglut3
    - freeglut3-dev
    - libnotify-dev

before_install:
  - sudo apt-get update -qq  # make sure package indexes are up to date
  - "export DISPLAY=:99.0"  # make the GUI testing work with the host machine display
  - "sh -e /etc/init.d/xvfb start"

  # - echo $DISPLAY
  # - export DISPLAY=unix:0.0
  # - export DISPLAY=localhost:0
  # - echo $DISPLAY
#virtualenv:
#  system_site_packages: true
install:
  - pip install scripttest pandas libtiff matplotlib numpy scipy future
  - sudo apt-get update
  - wget "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04/wxPython-4.0.0b1-cp35-cp35m-linux_x86_64.whl"
  - pip install wxPython-4.0.0b1-cp35-cp35m-linux_x86_64.whl
  # command to run tests, e.g. python setup.py test
script:

  #- python -m unittest unittests.test_ipmag unittests.test_imports SPD.tests.test_arai_plot_statistics SPD.tests.test_curvature SPD.tests.test_directional_statistics SPD.tests.test_ptrm_statistics SPD.tests.test_tail_check_statistics SPD.tests.test_additivity_check_statistics
  #- python -m unittest discover
  - python -c "print('yay')"
  - python -m unittest pmagpy_tests.test_pmag pmagpy_tests.test_pmag_gui
