language: python
python:
    #- "2.7"
    - "3.5.3" # currently breaks with 3.6, possibly need a different version of wxPython for 3.6
    # command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors

addons:
  apt:
    packages: # basically wxPython dependencies
    - libwebkitgtk-dev
    - libjpeg-dev
    - libtiff-dev
    - libgtk2.0-dev
    - libsdl1.2-dev
    - libgstreamer-plugins-base0.10-dev
    - freeglut3
    - freeglut3-dev
    - libnotify-dev

before_install:
  - sudo apt-get update -qq  # make sure package indexes are up to date
  - "export DISPLAY=:99.0"  # make the GUI testing work with the host machine display
  - "sh -e /etc/init.d/xvfb start"

# these lines were causing problems with wxPython
#virtualenv:
#  system_site_packages: true
install:
  - pip install scripttest pandas!=0.23.1 libtiff matplotlib numpy scipy future
  - sudo apt-get update
  - wget "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04/wxPython-4.0.0b1-cp35-cp35m-linux_x86_64.whl"
  # possibly should update this version of wxPython
  - pip install wxPython-4.0.0b1-cp35-cp35m-linux_x86_64.whl
  # command to run tests, e.g. python setup.py test
script:
  - python -c "print('starting tests')"
  - python -m unittest discover


# https://stackoverflow.com/questions/29290011/using-travis-ci-with-wxpython-tests
